package projectPart1;  // third party
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;


import java.util.*; 



public class WebEmailService {


	public void sendEmail(String email , List<Home> homesIn) { 
		//List<Home> homesIn
		System.out.print("hiii");
		String to = email;

	      // Put sender’s address
	      String from = "ysaberkh@gmail.com";
	      final String username = "49675f460af668";//username generated by Mailtrap
	      final String password = "8fe8ef0a6834b5";//password generated by Mailtrap

	      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
	      String host = "smtp.mailtrap.io";

	      Properties props = new Properties();
	      props.put("mail.smtp.auth", "true");
	      
	      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap  
	      props.put("mail.smtp.host", host);
	      props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

	      // Get the Session object.
	      Session session = Session.getInstance(props,
	         new javax.mail.Authenticator() {
	            protected PasswordAuthentication getPasswordAuthentication() {
	               return new PasswordAuthentication(username, password);
	    }
	         });

	      try {
	    // Create a default MimeMessage object.
	    Message message = new MimeMessage(session);
	 
	    // Set From: header field 
	    message.setFrom(new InternetAddress(from));
	 
	    // Set To: header field
	    message.setRecipients(Message.RecipientType.TO,
	               InternetAddress.parse(to));
	 
	    // Set Subject: header field
	    message.setSubject("List of requierd homes");
	 
	    // Put the content of your message
	    
	    String homeListString = "";
	    for(int i=0;i<homesIn.size();i++) {
       	 homeListString =  homesIn.get(i).toString()+ "\n";
        }
	    
	    message.setText( homeListString);

	    // Send message
	    Transport.send(message);

	    System.out.println("Sent message successfully....");

	      } catch (MessagingException e) {
	         throw new RuntimeException(e);
	      }
		


	}
	}
